---
- name: Debian| add repository OpenIO
  apt_repository:
    repo: "deb {{ sds_openio_repo }}/{{ ansible_distribution }}/ {{ ansible_distribution_release }}/"
    state: present
    filename: 'openio-sds'

- name : Debian| add repo key OpenIO
  apt_key:
    url: "http://mirror.openio.io/pub/repo/openio/APT-GPG-KEY-OPENIO-0"
    keyring: /etc/apt/trusted.gpg.d/openio.gpg  

- name : Debian| Install OpenIO puppet module
  apt:
    name: puppet-module-openio-openiosds
    update_cache: yes
...
