---
- name: Run the manifest
  command: puppet apply --no-stringify_facts /root/openio.pp
  register: puppet_result
  changed_when: puppet_result.rc == 2
  failed_when: puppet_result.rc == 1

- name: Bootstrap Zookeeper
  #command: zk-bootstrap.py OPENIO --lazy
  command: zk-bootstrap.py OPENIO
  when: 
    - ansible_host == conscience_ip 

- name: Meta0 service initialization
  command: openio --oio-ns=OPENIO cluster unlockall
  when: 
    - ansible_host == conscience_ip 

- name: Specify number of replicates for meta1 services
  command: "openio --oio-ns=OPENIO directory bootstrap --replicas {{ cluster_ip | length }}"
  when: 
    - ansible_host == conscience_ip 

- name: Meta0 restart
  command: gridinit_cmd restart @meta0

- name: Meta1 restart
  command: gridinit_cmd restart @meta1

- name: Start all services
  command: gridinit_cmd start

- name: Unlock all services in the namespace
  command: openio --oio-ns=OPENIO cluster unlockall
  when: 
    - ansible_host == conscience_ip 
...
